# Generated by Django 3.2.8 on 2021-10-22 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Surveyors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('STDE', models.FloatField()),
                ('MTDE', models.FloatField()),
                ('SUDEM', models.FloatField()),
                ('SUDEC', models.FloatField()),
                ('MVDEH', models.FloatField()),
                ('MVDEV', models.FloatField()),
                ('MVDEA', models.FloatField()),
                ('SVDEH', models.FloatField()),
                ('SVDEV', models.FloatField()),
                ('FD', models.FloatField()),
            ],
        ),
    ]
