# Generated by Django 3.2.8 on 2021-10-22 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoAPI', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Surveyors',
            new_name='Surveyor',
        ),
    ]
