# Generated by Django 3.2.8 on 2021-10-22 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoAPI', '0002_rename_surveyors_surveyor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveyor',
            name='FD',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='surveyor',
            name='SUDEC',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='surveyor',
            name='SUDEM',
            field=models.IntegerField(),
        ),
    ]
