# Generated by Django 3.2.8 on 2021-10-23 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoAPI', '0003_auto_20211022_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveyor',
            name='STDE',
            field=models.FloatField(verbose_name='Shaft drive-end temperature reading'),
        ),
    ]
