# Generated by Django 3.2.8 on 2021-10-23 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoAPI', '0004_alter_surveyor_stde'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveyor',
            name='FD',
            field=models.IntegerField(verbose_name='feed capacity'),
        ),
        migrations.AlterField(
            model_name='surveyor',
            name='MTDE',
            field=models.FloatField(verbose_name='Motor Drive-end Temperature Reading'),
        ),
        migrations.AlterField(
            model_name='surveyor',
            name='MVDEA',
            field=models.FloatField(verbose_name='Motor drive-end axial velocity'),
        ),
        migrations.AlterField(
            model_name='surveyor',
            name='MVDEH',
            field=models.FloatField(verbose_name='Motor drive-end vertical velocity'),
        ),
        migrations.AlterField(
            model_name='surveyor',
            name='MVDEV',
            field=models.FloatField(verbose_name='Motor drive-end horizontal velocity'),
        ),
        migrations.AlterField(
            model_name='surveyor',
            name='STDE',
            field=models.FloatField(verbose_name='Shaft Drive-end Temperature Reading'),
        ),
        migrations.AlterField(
            model_name='surveyor',
            name='SUDEC',
            field=models.IntegerField(verbose_name='Shaft drive-end carpet decibel reading'),
        ),
        migrations.AlterField(
            model_name='surveyor',
            name='SUDEM',
            field=models.IntegerField(verbose_name='Shaft drive-end maximum decibel reading'),
        ),
        migrations.AlterField(
            model_name='surveyor',
            name='SVDEH',
            field=models.FloatField(verbose_name='Shaft drive-end horizontal velocity'),
        ),
        migrations.AlterField(
            model_name='surveyor',
            name='SVDEV',
            field=models.FloatField(verbose_name='Shaft drive-end vertical velocity'),
        ),
    ]
